class_list = [
            #hidrografia
            [
            "Area_Umida_A",
            "Banco_Areia_A",
            "Corredeira_A",
            "Foz_Maritima_L",
            "Massa_Dagua_A",
            "Recife_A",
            "Rocha_Em_Agua_A",
            "Terreno_Sujeito_Inundacao_A",
            "Trecho_Drenagem_L",
            "Trecho_Massa_Dagua_A"
            ]
            ,
            #vegetação
            [
            "Brejo_Pantano_A",
            "Caatinga_A",
            "Campinarana_A",
            "Campo_A",
            "Cerrado_Cerradao_A",
            "Floresta_A",
            "Mangue_A",
            "Veg_Cultivada_A"
            ]
        ]